/**
 * Generate BRC-100 identities for every agent in the marketplace and
 * append them to .env in the format expected by wallet-toolbox's
 * Setup.getEnv('test'/'main').
 *
 * Run: npx tsx scripts/setup-brc-wallets.ts
 */
import { PrivateKey } from '@bsv/sdk'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'

const AGENTS = [
  'gateway',
  'weather', 'translate', 'summarize', 'price', 'geocode',
  'evm-compute', 'wasm-compute', 'gas-oracle', 'metering',
] as const

type AgentName = typeof AGENTS[number]

interface AgentIdentity {
  privKeyHex: string
  identityKey: string  // public key hex
  filePath: string     // sqlite db path
}

const REGISTRY_FILE = '.brc-identities.json'

function loadRegistry(): Record<string, AgentIdentity> {
  if (!existsSync(REGISTRY_FILE)) return {}
  return JSON.parse(readFileSync(REGISTRY_FILE, 'utf-8'))
}

function saveRegistry(reg: Record<string, AgentIdentity>): void {
  writeFileSync(REGISTRY_FILE, JSON.stringify(reg, null, 2))
}

function makeIdentity(name: AgentName): AgentIdentity {
  const k = PrivateKey.fromRandom()
  return {
    privKeyHex: k.toString(),  // hex
    identityKey: k.toPublicKey().toString(),
    filePath: `.wallet-storage/${name}.db`,
  }
}

function main() {
  if (!existsSync('.wallet-storage')) mkdirSync('.wallet-storage')

  const reg = loadRegistry()
  let added = 0
  for (const name of AGENTS) {
    if (!reg[name]) {
      reg[name] = makeIdentity(name)
      added++
    }
  }
  saveRegistry(reg)
  console.log(`${added} new identities added (total: ${Object.keys(reg).length})`)

  // Now build the .env block that wallet-toolbox expects.
  // We use the GATEWAY identity as the "primary" MY_TEST_IDENTITY (the one
  // returned by Setup.getEnv when no override is given). Per-agent wallets
  // use rootKeyHex override to swap identities at runtime.
  const gateway = reg.gateway
  const second = reg.weather  // any other identity for MY_TEST_IDENTITY2
  const devKeys: Record<string, string> = {}
  for (const [name, ident] of Object.entries(reg)) {
    devKeys[ident.identityKey] = ident.privKeyHex
  }

  const taalKey = process.env.TAAL_TESTNET_KEY || readEnv('TAAL_TESTNET_KEY') || 'testnet_d5baef21372e128894479d5d993202a6'
  const mainTaal = process.env.TAAL_MAINNET_KEY || readEnv('TAAL_MAINNET_KEY') || 'mainnet_90031b292de0767b72dcdff75945c3cc'

  const envBlock = `
# === wallet-toolbox BRC identities (generated by setup-brc-wallets.ts) ===
MY_TEST_IDENTITY='${gateway.identityKey}'
MY_TEST_IDENTITY2='${second.identityKey}'
MY_MAIN_IDENTITY='${gateway.identityKey}'
MY_MAIN_IDENTITY2='${second.identityKey}'
MY_TEST_FILEPATH='${gateway.filePath}'
MY_MAIN_FILEPATH='.wallet-storage/gateway-main.db'
TEST_TAAL_API_KEY='${taalKey}'
MAIN_TAAL_API_KEY='${mainTaal}'
DEV_KEYS='${JSON.stringify(devKeys)}'
MYSQL_CONNECTION='{}'
# === end wallet-toolbox block ===
`.trim()

  // Update .env: strip any existing block, append fresh
  let env = existsSync('.env') ? readFileSync('.env', 'utf-8') : ''
  const startMarker = '# === wallet-toolbox BRC identities'
  const endMarker = '# === end wallet-toolbox block ==='
  const startIdx = env.indexOf(startMarker)
  if (startIdx >= 0) {
    const endIdx = env.indexOf(endMarker, startIdx)
    if (endIdx >= 0) {
      env = env.slice(0, startIdx) + env.slice(endIdx + endMarker.length)
    }
  }
  env = env.trimEnd() + '\n\n' + envBlock + '\n'
  writeFileSync('.env', env)

  console.log(`\nAgent identities:`)
  for (const [name, ident] of Object.entries(reg)) {
    console.log(`  ${name.padEnd(15)} ${ident.identityKey.slice(0, 20)}…  →  ${ident.filePath}`)
  }
  console.log(`\n.env block written. ${Object.keys(devKeys).length} keys in DEV_KEYS.`)
}

function readEnv(key: string): string | undefined {
  if (!existsSync('.env')) return undefined
  const m = readFileSync('.env', 'utf-8').match(new RegExp(`^${key}=(.*)$`, 'm'))
  return m?.[1]
}

main()
